name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'ProcessStub-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/RTCV'
        ref: '506v2'
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore Nuget packages in RTCV
      run: msbuild /t:restore '.\RTCV\'
    - name: Restore Nuget packages in ProcessStub-Vanguard
      run: msbuild /t:restore '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'
    - name: Build with MSBuild
      run: msbuild '.\ProcessStub-Vanguard\ProcessStub-Vanguard.sln'
